apiVersion: v1
kind: Pod
metadata:
  name: space-invaders
  namespace: default
  labels:
    app: space-invaders
spec:
  restartPolicy: Always
  containers:
    - name: game
      image: localhost:32000/space-invaders:latest
      imagePullPolicy: Always
